# https://github.com/xdspacelab/openvslam/issues/104
# http://www.huyaoyu.com/technical/2018/06/23/convert-results-from-ros-camera_calibration-into-format-used-by-opencv.html


Camera.name: "Bebop 1"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 396.17782
Camera.fy: 399.798333
Camera.cx: 322.453185
Camera.cy: 174.243174

Camera.k1: -0.001983
Camera.k2: 0.015844
Camera.p1: -0.003171
Camera.p2: 0.001506
Camera.k3: 0.0

Camera.fps: 30.0
Camera.cols: 640
Camera.rows: 368

Camera.color_order: "RGB"

#================#
# orb parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#========================#
# Initializer Parameters #
#========================#

Initializer.scaling_factor: 5.0
